# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Chen's Blog

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-cn
  contentDir: content/zh
  title: 陈李粮的碎碎念
  menu:
     main:
       - name: 碎碎念
         url: post
         weight: 20
       - name: 光和影
         url: people
         weight: 30
       - name: 独行侠
         url: event
         weight: 40
       - name: 文档库
         url: publication
         weight: 50
       - name: 联系我
          url: contact
         weight: 60
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
